### PR TITLE
[helm] Fix for param name and probes

### PR DESCRIPTION
**Pull request by albundy83**
Hello,
I have made an error in the previous merge request, sorry for that.

The idea to pull /metrics to perform the readiness and liveness probes was a terrible idea, it totally overload the api calls (especially if you did not disable oos count)
So, I remove it.
Docker need to be rebuilt by the way, should I update release version also ?

### CODE REVIEW

**Comment by albundy83** [comment]
Well, even with the `tcpSocket`, nc command is triggered.
Until, osc-cost has a better /metrics, I should disable livenessProbe and readinessProbe

What do you think ?

**Comment by outscale-vbr** [comment]
Hi, Thanks for your PR.
You are right using /metrics is a bad idea because you will overload the api calls.
I agree to have for the moment tcpSocket on port 8080 so that probes only check that osc-cost server doesn't crash.
In the future, we can consider having a specific call to check that osc-cost exporter is healthy.
PS I have created a PR to prepare the release (helm, docker, cargo version) for your PR (https://github.com/outscale/osc-cost/pull/108)

**Comment by albundy83** [comment]
Well, for the tcpSocket, as I told you, I have tried it and it seems that it also trigger the api calls :( ...
That's why I was thinking about removing for moment the *probes
(Your PR is perfect :) )

**Comment by outscale-vbr** [comment]
Ok to disable livenessProbe and readinessProbe

**Comment by albundy83** [comment]
Ok done :)

**Pull request merged**
